export const statusOptions = [
  { key: "available", label: "Available" },
  { key: "active", label: "Active" },
  { key: "new_listing", label: "New Listing" },
  { key: "price_reduced", label: "Price Reduced" },
  { key: "pending", label: "Pending" },
  { key: "under_contract", label: "Under Contract" },
  { key: "contingent", label: "Contingent" },
  { key: "in_escrow", label: "In Escrow" },
  { key: "sold", label: "Sold" },
  { key: "rented", label: "Rented" },
  { key: "leased", label: "Leased" },
  { key: "off_market", label: "Off Market" },
  { key: "temporarily_unavailable", label: "Temporarily Unavailable" },
  { key: "maintenance", label: "Maintenance" },
  { key: "withdrawn", label: "Withdrawn" },
  { key: "cancelled", label: "Cancelled" },
  { key: "expired", label: "Expired" },
];

export const typeOptions = [
  { key: "house", label: "House" },
  { key: "apartment", label: "Apartment" },
  { key: "condo", label: "Condo" },
  { key: "townhouse", label: "Townhouse" },
  { key: "villa", label: "Villa" },
  { key: "penthouse", label: "Penthouse" },
  { key: "studio", label: "Studio" },
  { key: "duplex", label: "Duplex" },
  { key: "loft", label: "Loft" },
  { key: "bungalow", label: "Bungalow" },
  { key: "cottage", label: "Cottage" },
  { key: "mansion", label: "Mansion" },
];

export const propertyTypes = [
  { key: "house", label: "House" },
  { key: "apartment", label: "Apartment" },
  { key: "condo", label: "Condo" },
  { key: "townhouse", label: "Townhouse" },
  { key: "villa", label: "Villa" },
  { key: "penthouse", label: "Penthouse" },
  { key: "studio", label: "Studio" },
  { key: "duplex", label: "Duplex" },
  { key: "triplex", label: "Triplex" },
  { key: "loft", label: "Loft" },
  { key: "bungalow", label: "Bungalow" },
  { key: "cottage", label: "Cottage" },
  { key: "mansion", label: "Mansion" },
  { key: "farmhouse", label: "Farmhouse" },
  { key: "cabin", label: "Cabin" },
  { key: "mobile_home", label: "Mobile Home" },
  { key: "tiny_home", label: "Tiny Home" },
  { key: "office_building", label: "Office Building" },
  { key: "retail_building", label: "Retail Building" },
  { key: "industrial_building", label: "Industrial Building" },
  { key: "warehouse_building", label: "Warehouse Building" },
  { key: "restaurant_building", label: "Restaurant Building" },
  { key: "hotel_building", label: "Hotel Building" },
  { key: "resort_building", label: "Resort Building" },
  { key: "shopping_center_building", label: "Shopping Center Building" },
  { key: "mall_building", label: "Mall Building" },
  { key: "factory_building", label: "Factory Building" },
  { key: "storage_building", label: "Storage Building" },
  { key: "parking_structure", label: "Parking Structure" },
  { key: "land", label: "Land" },
  { key: "plot", label: "Plot" },
  { key: "farm_land", label: "Farm Land" },
  { key: "orchard_land", label: "Orchard Land" },
  { key: "vineyard_land", label: "Vineyard Land" },
  { key: "ranch_land", label: "Ranch Land" },
  { key: "plantation_land", label: "Plantation Land" },
];

export const propertyCategories = [
  { key: "residential", label: "Residential" },
  { key: "luxury_residential", label: "Luxury Residential" },
  { key: "student_housing", label: "Student Housing" },
  { key: "senior_living", label: "Senior Living" },
  { key: "vacation_home", label: "Vacation Home" },
  { key: "affordable_housing", label: "Affordable Housing" },
  { key: "office", label: "Office" },
  { key: "retail", label: "Retail" },
  { key: "industrial", label: "Industrial" },
  { key: "warehouse", label: "Warehouse" },
  { key: "mixed_use", label: "Mixed Use" },
  { key: "hospitality", label: "Hospitality" },
  { key: "healthcare", label: "Healthcare" },
  { key: "education", label: "Education" },
  { key: "religious", label: "Religious" },
  { key: "agricultural", label: "Agricultural" },
  { key: "land_development", label: "Land Development" },
  { key: "vacant_land", label: "Vacant Land" },
  { key: "investment", label: "Investment" },
  { key: "new_construction", label: "New Construction" },
  { key: "foreclosure", label: "Foreclosure" },
];

export const propertyStatuses = [
  { key: "available", label: "Available" },
  { key: "active", label: "Active" },
  { key: "new_listing", label: "New Listing" },
  { key: "price_reduced", label: "Price Reduced" },
  { key: "pending", label: "Pending" },
  { key: "under_contract", label: "Under Contract" },
  { key: "contingent", label: "Contingent" },
  { key: "in_escrow", label: "In Escrow" },
  { key: "sold", label: "Sold" },
  { key: "rented", label: "Rented" },
  { key: "leased", label: "Leased" },
  { key: "off_market", label: "Off Market" },
  { key: "temporarily_unavailable", label: "Temporarily Unavailable" },
  { key: "maintenance", label: "Maintenance" },
  { key: "withdrawn", label: "Withdrawn" },
  { key: "cancelled", label: "Cancelled" },
  { key: "expired", label: "Expired" },
];

export const featuresOptions = [
  { key: "furnished", label: "Furnished" },
  { key: "unfurnished", label: "Unfurnished" },
  { key: "semi_furnished", label: "Semi-Furnished" },
  { key: "pet_friendly", label: "Pet Friendly" },
  { key: "smoking_allowed", label: "Smoking Allowed" },
  { key: "wheelchair_accessible", label: "Wheelchair Accessible" },
];

export const amenitiesOptions = [
  { key: "air_conditioning", label: "Air Conditioning" },
  { key: "heating", label: "Heating" },
  { key: "parking", label: "Parking" },
  { key: "swimming_pool", label: "Swimming Pool" },
  { key: "gym", label: "Gym" },
  { key: "security", label: "Security" },
  { key: "elevator", label: "Elevator" },
  { key: "balcony", label: "Balcony" },
  { key: "garden", label: "Garden" },
  { key: "fireplace", label: "Fireplace" },
];
